from datetime import timedelta

DB_NAME = 'DB_NAME'
DB_USER = 'DB_USER'
DB_PASSWORD = 'DB_PASSWORD'
DB_HOST = '127.0.0.1'
DB_PORT = '3306'

SECRET_KEY = 'SECRET_KEY'
ALGORITHM = 'ALGORITHM'
ACCESS_TOKEN_LIFETIME = timedelta(days=2)
REFRESH_TOKEN_LIFETIME = timedelta(days=7)
PAGE_SIZE = 5